### ISSUE TITLE
AllelicCNV input files

### ISSUE THREAD

**Issue by erleholgersen** [broadinstitute/deTiN#13]
Hello,

I've been going through the GATK pre-processing steps to generate all of the input files for DeTiN. I ran into an error in the AllelicCNV (missing Spark dependency), and googling the issue led to a GitHub issue that concluded with the entire CNV pipeline being deprecated:
https://github.com/broadinstitute/gatk/issues/3599

Is there an alternative way to generate these files going forward? 

Thanks!

**Comment by amarotaylor** [comment]
Hey Erle,
Sorry to hear that.. I am not on the GATK team and often have trouble keeping track of where they're at in terms of development especially with the copy number tools. However, AllelicCNV doesn't seem to be deprecated: 
https://software.broadinstitute.org/gatk/documentation/tooldocs/4.beta.6/org_broadinstitute_hellbender_tools_exome_AllelicCNV.php
Might I suggest running GATK using Docker? It might be easier than building the GATK yourself which I find often leads to problems. 
https://hub.docker.com/r/broadinstitute/gatk/

**Comment by amarotaylor** [comment]
If you're looking for an alternative to GATK you could try facets. https://github.com/mskcc/facets. I would be happy to either add code or merge a pull request which supports the output of that their model.

**Comment by erleholgersen** [comment]
Thanks! I got AllelicCNV to work in a Docker container, using these instructions (and increasing the memory allocated to Docker):
https://gatkforums.broadinstitute.org/gatk/discussion/10870/howto-run-gatk4-in-a-docker-container

**Comment by petrsha** [comment]
Hi,

how did you generate SNPs Interval List file, please? I downloaded this gs://broad-references/hg19/v0/dbsnp_135.b37.vcf.gz and then convert it to a list file using 'VcfToIntervalList'. But when I run GetBayesianHetCoverage I got the following error 'htsjdk.samtools.SAMException: Intervals not in order: 19:59118797-59118797	+	rs192113880; 2:10133-10133	+	rs187078949' .  I tried to sort that file but I got 'java.lang.ArrayIndexOutOfBoundsException: 17518'. Then I also tried it with 'GetHetCoverage' since I found out that GetBayesianHetCoverage is being deprecated(https://gatkforums.broadinstitute.org/gatk/discussion/10844/allelic-cnv-common-snps-and-getbayesianhetcoverage), but I got same errors (using GATK in a Docker container). Any help would be really appreciated.

**Comment by Admera2020** [comment]
Hello, 

> If you're looking for an alternative to GATK you could try facets. https://github.com/mskcc/facets. I would be happy to either add code or merge a pull request which supports the output of their model.

Is this still a possibility to incorporate Facets? Given the GATK's "AllelicCNV" is indeed replaced by a tool that doesn't produce output required by "DE-tin" see here https://github.com/broadinstitute/gatk/issues/6685
On the other hand, https://github.com/mskcc/facets seems quite straightforward. 

P.S the link to GATK from DeTiN from Wiki doesn't seem to work anymore. 

Thank you for your help in advance. 
Best, 
Nihir
