### ISSUE TITLE
How can we get the value "tau" in aSCNA segmentation file?

### ISSUE THREAD

**Issue by Chitanda-Satou** [broadinstitute/deTiN#21]
Dear @amarotaylor, I have sawn that in the description of aSCNA segmentation file, the value "tau" is that:

> Two centered segment copy ratio data. Copy ratio is the relative amount of DNA in the tumor sample at the segment compared to normal (or a panel of normals). We use this ratio plus 2.  

Does it mean that:  

 _**tau = N(tumor) / N(normal) + 2**_   ?

However, in the example data "HCC-1143_100_T-sim-final.acs.seg", we can see many tau values are smaller than 2. If I did not make a misunderstanding, tau should not be smaller than 2.

Could you tell me how to calculate tau? Thanks a lot!

Best regards.

**Comment by amarotaylor** [comment]
Ah sorry for the confusion. Tau is the observed copy ratio in the tumor data, that is the purity (a) weighted copy number for tumor cells (t) and normals (n).  
Tau = a*t + (1-a)*n
Since we don't observe purity in practice the measured copy ratio in GATK is the ratio of tumor coverage to normal coverage. The value tau is normalized so that at t=n, tau = 2. Does that clarify things? You should be able to get more information from the GATK forums since they're method generates Tau in our files.

**Comment by Chitanda-Satou** [comment]
> Ah sorry for the confusion. Tau is the observed copy ratio in the tumor data, that is the purity (a) weighted copy number for tumor cells (t) and normals (n).
> Tau = a*t + (1-a)*n
> Since we don't observe purity in practice the measured copy ratio in GATK is the ratio of tumor coverage to normal coverage. The value tau is normalized so that at t=n, tau = 2. Does that clarify things? You should be able to get more information from the GATK forums since they're method generates Tau in our files.

Thank you for your excellent work!
